# Generated by Django 2.2.12 on 2020-06-02 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_datetime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
