# Generated by Django 2.2.12 on 2020-06-02 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts_app', '0002_auto_20200603_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_datetime',
            field=models.DateTimeField(null=True),
        ),
    ]
