# Generated by Django 2.2.12 on 2020-06-14 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts_app', '0004_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
