# Generated by Django 2.2.12 on 2020-06-14 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts_app', '0006_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='text',
            new_name='comment',
        ),
    ]
