# Generated by Django 2.2.12 on 2020-06-19 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts_app', '0008_auto_20200619_2253'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reply',
        ),
    ]
