# Generated by Django 2.2.12 on 2020-06-21 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts_app', '0012_auto_20200621_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='reply',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='replytoreply',
            name='this_reply',
            field=models.CharField(max_length=500),
        ),
    ]
