# Generated by Django 2.2.12 on 2020-06-23 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts_app', '0014_auto_20200621_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='commentator',
            field=models.CharField(max_length=50),
        ),
    ]
