# Generated by Django 2.2.12 on 2020-06-23 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts_app', '0015_auto_20200623_1840'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(error_messages={'blank': 'First name field cant be blank.'}, max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('contact_no', models.IntegerField()),
                ('location', models.CharField(max_length=50)),
                ('reason_for_contact', models.CharField(choices=[('GI', 'General Information'), ('IAALP', 'I am a liver patient'), ('IAAFFOALP', 'I am a friend/family of a liver patient'), ('IAALD', 'I am a living donor'), ('IROR', 'Information regarding organ registration'), ('Other', 'Other')], max_length=2)),
            ],
        ),
    ]
