# Generated by Django 2.2.12 on 2020-06-23 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts_app', '0016_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='datetime',
            field=models.TimeField(null=True),
        ),
    ]
