# Generated by Django 2.2.12 on 2020-06-24 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts_app', '0017_contact_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='reason_for_contact',
            field=models.CharField(choices=[('GI', 'General Information'), ('IAALP', 'I am a liver patient'), ('IAAFFOALP', 'I am a friend/family of a liver patient'), ('IAALD', 'I am a living donor'), ('IROR', 'Information regarding organ registration'), ('Other', 'Other')], default='GI', max_length=10),
        ),
    ]
