# Generated by Django 2.2.12 on 2020-06-24 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts_app', '0018_auto_20200624_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='respondent',
            field=models.CharField(max_length=50),
        ),
    ]
