# Generated by Django 2.2.12 on 2020-06-25 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts_app', '0019_auto_20200624_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='replytoreply',
            name='reply_respondent',
            field=models.CharField(max_length=50),
        ),
    ]
