# Generated by Django 2.2.12 on 2020-06-25 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts_app', '0020_auto_20200625_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='respondent',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='replytoreply',
            name='reply_respondent',
            field=models.CharField(max_length=15),
        ),
    ]
