# Generated by Django 2.2.12 on 2020-06-28 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts_app', '0021_auto_20200626_0033'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReplyToReply',
        ),
    ]
